name: auditor-seo

services:
  seo-monitor:
    build:
      context: .
    container_name: auditor-seo
#    restart: unless-stopped
    ports:
      - "${PORT:-3017}:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "file:/data/prod.db"
    volumes:
      - auditor-seo-data:/data

volumes:
  auditor-seo-data:
    name: auditor-seo-data
